# Generated by Django 5.2.4 on 2025-08-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userverification_usercoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoin',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
